### ISSUE TITLE
feature request: add new method Async::exist

### ISSUE THREAD

**Issue by Sherlock-Holo** [smol-rs/smol#142]
since `async-std` has used `smol` as the runtime, their `TcpStream` is a wrapper about `Async<std::net::TcpStream>`, that makes we can't use `Async` wrap it again and do something with `read_with`, `write_with` or use `readable()` and `writable` (which in PR #141).

If we can add a new method for `Async<T>` like

```rust
/// Create a new async I/O handle, if io's fd has been registered in `Async`, or return `None`.
pub fn exist(io: T) -> Option<Async<T>>
```

## how to do this

In Unix we know in a process, if `fd1 == fd2`, that means both of them are referenced to the same thing, such as file description, socket, or anything else. So we can check `Reactor` if any `Source` has the same fd, if it exists, clone the `Arc<Source>` and return a new `Async` but references to the same fd.

I'm not good at Windows program but I see the `RawSocket` is a type alias for u64, so it maybe can work like in Unix.

**Comment by stjepang** [comment]
Is there are a use case for wrapping async-std's `TcpStream` into `Async`?

I'm not sure I understand the motivation for this :) Is it to prevent accidental bugs? Or does it add new functionality?

**Comment by Sherlock-Holo** [comment]
I'm trying to make `splice(2)` async. When I get an `std::net::TcpStream` and a pipe from `os_pipe` crate, I use `nix::fcntl::splice` with non-block mode to copy data. 

With the new async functions in PR #141, I can wait until the tcp stream is readable and the pipe is writable through wrapping them with `Async`. 

However if the tcp stream is `async_std::net::Tcpstream`, because it is just a wrapper of `Async<std::net::Tcpstream>`, if I wrap the `async_std::net::Tcpstream` with `Async` again, it will return `AlreadyExists` error because we can't register a fd into an epoll twice.

That means if I want to use `Async`, I need to avoid using `async_std` crate to ensure there's no fd will register into an epoll twice, that doesn't look good.

**Comment by Sherlock-Holo** [comment]
or perhaps we can add a check in `Async::new`:

first call `insert_io` directly, if return error and error kind is `AlreadyExists`, then we check if `smol` reactor has a `Source` that have the same fd, if it has, clone the `Arc<Source>` and return an `Async`, otherwise just return the error

**Comment by Sherlock-Holo** [comment]
I think check fd is registered in `Async::new` is a better way, that doesn't need to add a new api.

I have a fork and added this feature https://github.com/Sherlock-Holo/smol/commit/676bb2bc7e6ff39b4aff4c4f362acdcc1f32a526

If you need, I can create a PR :)

**Comment by stjepang** [comment]
I'm not sure how I feel about this feature. I'd probably try to avoid adding it unless it's really really useful. :)

@Sherlock-Holo It's been a while now - do you still have a need for this kind of API?

**Comment by Sherlock-Holo** [comment]
yes, i am still need it, if you add this feature, i will be pleasure

**Comment by notgull** [comment]
This API is a probable foot gun that can't be implemented efficiently.
