### ISSUE TITLE
Multiple servers example

### ISSUE THREAD

**Issue by mhristache** [smol-rs/smol#211]
Hi

I have an application that listens on multiple ports. Currently I am implementing it using threads but I consider changing it to async. Can you provide an example on how I would implement multiple servers (listen on multiple ports and handle connections on each of those ports) using smol runtime?

Thank you

//Max

**Comment by stjepang** [comment]
You could do something like this:

```rust
use smol::prelude::*;

let l1 = TcpListener::bind("localhost:8000").await?;
let l2 = TcpListener::bind("localhost:8001").await?;
let l3 = TcpListener::bind("localhost:8002").await?;

loop {
    let (stream, addr) = l1.race(l2).race(l3).await?;
    println!("accepted client: {:?}", addr);
}
```
