### ISSUE TITLE
Feature request: Add FromRawFd to UnixStream

### ISSUE THREAD

**Issue by laptou** [smol-rs/smol#212]
I would like to be able to convert raw file descriptors into `UnixStream` without having to convert to `Async<std::os::unix::net::UnixStream>` first.

**Comment by notgull** [comment]
I don't believe that there's a way to implement `FromRawFd` on `UnixStream` without introducing a potential panic. Given that smol-rs/async-net#21 introduces a way to convert an `OwnedFd` to a `UnixStream` using `TryFrom`, and how one can unsafely convert a `RawFd` to an `OwnedFd`, this issue should be resolved.
