### ISSUE TITLE
Example for using new executor model

### ISSUE THREAD

**Issue by rachel-rose** [smol-rs/smol#213]
I have been refactoring my program to adopt smol's recent executor redesign.

I am creating an executor within a main function, like so:

```rust
let executor = Arc::new(Executor::new());

```

I want to pass the exectutor into various tasks throughout the program so I can spawn tasks inside of tasks.
I do this by passing a clone to the executor inside the task function:

```rust
pub async fn start_connection(executor: Arc<Executor<'_>>)

```

Having passed a clone to the task, I then spawn a new task inside it using the cloned executor.

```rust
let task = executor.spawn(async move {
            loop {
                // ... do something
            }
        });
```

I am looking for some examples to inform this code. An example of creating a thread pool where you spawn a main task would be really useful.

In a previous version of this program I was using multi-threaded executor from the [smol::run](https://docs.rs/smol/0.1.18/smol/fn.run.html) documentation. 

In this code, you can call `Task::spawn` inside of the task. Now I have switched to the [smol::Executor](https://docs.rs/smol/1.2.5/smol/struct.Executor.html) example in which we call `Executor::run` and it is not clear how to spawn a new task.

**Comment by rachel-rose** [comment]
I've now refactored this code to use references instead of Arc pointers. 

Declaring the executor in main:

```
let executor = Executor::new();
```

Passing a reference to the executor:

```
pub fn new(executor: &Executor<'_>)
```

This works fine until I try to spawn a task that uses the executor inside of a task:

```
async fn start(executor: &Executor<'_>) {
    let server_task = executor.spawn(async {
        executor.spawn(async { println!("hello"); }).await;
    });
}
```
Here is the error I've been getting:
```
| async fn start(executor: &Executor<'_>) {
   |                           ------------  -
   |                           |
   |                           this parameter and the return type are declared with different lifetimes...
...
18 |     let server_task = executor.spawn(async {
   |                                ^^^^^ ...but data from `executor` is returned here
```

**Comment by narodnik** [comment]
I'm curious of the correct answer, but managed to get this snippet to compile:
```rust
async fn bang<'a>(executor: &'a Executor<'a>) {
    let executor2 = executor.clone();
    let server_task = executor.spawn(async move {
        executor2
            .spawn(async {
                println!("hello");
            })
            .await;
    });
}
```

**Comment by narodnik** [comment]
I managed to isolate the cause of the above problem down to Executor's `drop` method:
```rust
impl Drop for Executor<'_> {
    fn drop(&mut self) {
        // ....
    }
}
```
if I delete this code then the snippet above compiles.

**Comment by narodnik** [comment]
OK I tried using `Arc` as in your first post and things seem to work well.

```rust
async fn foo(ex: async_dup::Arc<Executor<'_>>) -> io::Result<()> {
    let ex2 = ex.clone();

    ex.spawn(async move {
        ex2.spawn(async {
            println!("hello world");
        }).await;
    })
    .await;

    Ok(())
}

fn main() -> io::Result<()> {
    let ex = async_dup::Arc::new(Executor::new());
    let (signal, shutdown) = unbounded::<()>();

    let ex2 = ex.clone();

    Parallel::new()
        // Run four executor threads.
        .each(0..1, |_| future::block_on(ex.run(shutdown.recv())))
        // Run the main future on the current thread.
        .finish(|| {
            future::block_on(async move {
                foo(ex2).await;
                drop(signal);
            })
        });

    Ok(())
}
```

I'll wait for stjepang to confirm this is the recommended way first, but it seems to work fine.

**Comment by stjepang** [comment]
This is exactly how I'd do it, too. :) 

Just a minor note: there's no need for `async_dup::Arc` because `std::sync::Arc` should work just as well.

**Comment by rachel-rose** [comment]
Thank you both very much for your help, this has been very clarifying. Closing this issue :)
