### ISSUE TITLE
Make the documentation of Async::new explicit on the fact that it does not support regular files?

### ISSUE THREAD

**Issue by Ekleog** [smol-rs/smol#217]
Hey! I just got tricked by #61, and checking the documentation wasn't that helpful: I was thinking that smol somehow had some kind of dark magic to make it work even though it was a file.

Reading #61 I understood what was wrong in my code (and I have been able to easily replace `smol::Async` with `smol::Unblock`), but to get to it I had to `strace` my process and figure out that the “permission denied” that was reported was due to `epoll_ctl` failing.

Hence, a suggestion: what would you think about making the documentation for `Async::new` and `Unblock::new` point to each other so people cannot miss the fact that the two exist and each cover their own ground?

**Comment by shekohex** [comment]
Would you like to make a small PR for it? 😃

**Comment by rtyler** [comment]
a small smol PR would be appreciated

**Comment by notgull** [comment]
The documentation for [`Async`](https://docs.rs/async-io/latest/async_io/struct.Async.html) now says:

> However, do not use [Async](https://docs.rs/async-io/latest/async_io/struct.Async.html) with types like [File](https://doc.rust-lang.org/nightly/std/fs/struct.File.html), [Stdin](https://doc.rust-lang.org/nightly/std/io/stdio/struct.Stdin.html), [Stdout](https://doc.rust-lang.org/nightly/std/io/stdio/struct.Stdout.html), or [Stderr](https://doc.rust-lang.org/nightly/std/io/stdio/struct.Stderr.html) because all operating systems have issues with them when put in non-blocking mode.

This seems explicit enough to me.
