### ISSUE TITLE
Hyper Server Example is Broken

### ISSUE THREAD

**Issue by bastibl** [smol-rs/smol#219]
As @nickbp mentioned in #218, the hyper server example is broken at the moment.

According to my understanding, https://github.com/smol-rs/async-io/commit/aae2473a80da6727b636071ea60e164b5d273ff5 is the relevant change. This commit deletes wakers under some circumstances that I don't fully understand. I'm not sure if hyper breaks a contract here (by dropping references it is supposed to keep) or if async-io drops too eagerly. But if I delete the relevant lines (https://github.com/smol-rs/async-io/blob/master/src/reactor.rs#L482-L485), the example works (for http1).

It would be great if someone with more experience could have a look.

**Comment by taiki-e** [comment]
I think the following lines are causing the problem. As explained in https://github.com/smol-rs/async-io/pull/37#discussion_r501784717, it drops `incoming` every time `incoming.poll_next(cx)` returns `Pending` to reset the state.

https://github.com/smol-rs/smol/blob/76dac2a493a7e2e1356669008e847b94d1f89eb8/examples/hyper-server.rs#L100-L102
