### ISSUE TITLE
Panic: "There is no reactor running, must be called from the context of a Tokio 1.x runtime"

### ISSUE THREAD

**Issue by ClementNerma** [smol-rs/smol#238]
Hi there!

I've just set up a first application with `smol`, which basically looks like this:

```rust
fn main() {
    smol::block_on(test_async_fn())
}
```

When I run the application, I get the following output:

```
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/context.rs:21:19
```

Do you have any idea what this is caused by?

Thanks in advance!

**Comment by sdroege** [comment]
As the panic message suggests, your async function requires a tokio runtime and can't run on smol. You're using something inside the async function that only works with tokio.

**Comment by ClementNerma** [comment]
Oh, I thought the problem was coming from `smol`. I'm using `reqwest` so maybe that's where the problem comes from, I'll check this out.
Thanks for your help!

**Comment by sdroege** [comment]
reqwest requires tokio, yes
