### ISSUE TITLE
Give smol-rs a logo/mascot

### ISSUE THREAD

**Issue by notgull** [smol-rs/smol#240]
I think it'd be fun/cute to have a mascot for `smol-rs` that isn't the default autogenerated profile picture. Any thoughts on this? Here's a quick sketch of my suggestion: a mixture between a fly and a rabbit, combining "small" and "fast".

(Redacted)

**Comment by taiki-e** [comment]
(I thought the icon of [the discord server](https://discord.com/invite/x6m5Vvt) is the logo of smol-rs...)

**Comment by notgull** [comment]
Reopening this issue because of `smol` v2.0.0, where I think it would be fun to reimagine the logo. Here's my take: it's the orange tabby cat from the v1.0.0 logo, but this time it's cybernetically modified:

![image](https://github.com/smol-rs/smol/assets/19805233/a9bcefe8-9d27-4274-8505-19b368aa584d)

(This was drawn by [NebulousStar](https://twitter.com/star_nebulous), thank you!)

Thoughts on this?

**Comment by notgull** [comment]
@smol-rs/admins Thoughts on this? If the answer is yes I would need Owner permissions to set the GitHub organization logo
