### ISSUE TITLE
Should we expose event-listener in this crate?

### ISSUE THREAD

**Issue by notgull** [smol-rs/smol#272]
`Event` is a useful primitive that gets used in a lot of crates that also use `smol`. See [here](https://github.com/psychon/x11rb/blob/master/x11rb-async/src/rust_connection/shared_state.rs) for the implementation of `x11rb-async`, which makes extensive use of `event-listener` alongside `async-io` in order to drive an X11 connection.

Therefore as it is a commonly used primitive, exposing it in `async-lock` or `smol` would be a nice convenience for users. Are there any arguments against this?

**Comment by taiki-e** [comment]
I personally feel that event-listener belongs in the same category as the utilities that are not currently exposed on smol rather than the various crates that are exposed on smol, but I have no strong opinion on this.

**Comment by notgull** [comment]
I think there is a difference between `event-listener` and, say, `concurrent-queue`, which I personally think falls into the "shouldn't be exposed in `smol`" category.

If you look at the reverse dependencies for [`concurrent-queue`](https://crates.io/crates/concurrent-queue/reverse_dependencies), you can see that, outside of the crates used by `smol`, `concurrent-queue` is not used that often. In addition, `concurrent-queue` doesn't have much to do with `async/await` outside of its using in `async/await` crates.

In contrast, [`event-listener`](https://crates.io/crates/event-listener/reverse_dependencies) is heavily used outside of `smol` in crates like `zbus` and `sqlx`. In addition, `event-listener` is an important `async/await` primitive that directly ties into `smol`'s goals.

**Comment by notgull** [comment]
Deciding against
