### ISSUE TITLE
Figure out a way to race multiple futures in smol

### ISSUE THREAD

**Issue by notgull** [smol-rs/smol#292]
Generally in `smol` we frown on large combinators and prefer using the executor when possible. For instance, instead of `join`ing a bunch of different futures, we spawn the futures on an `Executor` and then wait on each of the `Task` handles.

However this isn't a good solution to `or` or `race`. Ideally we would have a way to spawn a bunch of futures on an `Executor` and then have a way to wait on one of those tasks.

cc @i509vcb, @smol-rs/admins Would appreciate brainstorming on a good solution to this problem, as one isn't immediately apparent to me.

**Comment by notgull** [comment]
One way of doing this would be with a channel.

```rust
let (sender, receiver) = async_channel::bounded(1);
let ex = Executor::new();

let mut handles = vec![];

// Spawn all of the futures.
for future in futures_to_race {
    handles.push(ex.spawn({
        let sender = send.clone();
        async move {
            // Send the result of the future down the channel.
            sender.send(future.await).await.ok();
        }
    });
}

// Run the executor while waiting for the result.
let result = ex.run(receiver.recv()).await.unwrap();
for handle in handles {
    handle.cancel().await;
}
```

However, this is pretty unwieldy and I would like a way to implement this pattern in a simpler way. Same could probably go for the `zip` and `or` patterns.

**Comment by fogti** [comment]
A fully generic channel looks a like a bit too much, why not e.g. a once_cell, an event and a flag (or just some kind of one-shot channel with clonable sending end)?

**Comment by notgull** [comment]
Although that would work, it's unfair to expect this burden to fall onto the user. My idea was to create an `async-executor-util` (name open to suggestions) crate to have all of the combinators that would be needed for this.

**Comment by fogti** [comment]
ok, oh some additional prior art would also be https://github.com/YZITE/server-executor, which I wrote to have an executor for tests, simple async servers, etc.

**Comment by notgull** [comment]
I think the [`futures-concurrency`](https://github.com/yoshuawuyts/futures-concurrency.git) crate provides a good solution to this problem for now, at least on the short scale. For larger scale futures we'll wait for a conclusion in smol-rs/futures-lite#93.
